
format="$directory$all$line_break$aws${custom.assume_role}$gcloud$character"

right_format = """
($kubernetes)
"""

command_timeout = 1000

[aws]
format = "[(awsp:\\($profile\\) )]($style)"

[crystal]
format = "[$symbol]($style) "

[custom.assume_role]
command = 'echo "aws:($AWS_ACCOUNT_ROLE@$AWS_ACCOUNT_NAME)" '
when = """
test "$AWS_ACCOUNT_ROLE" -a "$AWS_ACCOUNT_NAME"
"""

[directory]
truncate_to_repo = false
truncation_length = 10
truncation_symbol = "..."

[docker_context]
format = "[$symbol]($style) "

[gcloud]
format = "[(gcp:\\($project\\) )]($style)"

[git_branch]
format = "[$symbol$branch]($style) "

[kubernetes]
disabled = false
format = "[$symbol$context( \\($namespace\\))]($style)"

[nodejs]
format = "[$symbol]($style) "

[package]
format = "[$symbol]($style) "

[perl]
format = "[$symbol]($style) "

[python]
format = "[$symbol]($style) "

[ruby]
format = "[$symbol]($style) "

[terraform]
format = "[$symbol]($style) "

[golang]
format = "[$symbol]($style) "

